# http://about.travis-ci.org/docs/user/languages/python/
language: python

# which python versions
python:
  - "2.7"

# set environment variables
# env:
#   - DJANGO_VERSION=1.2.7

# install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# run tests
script: nosetests

# choose git branches
branches:
  only:
    - master

# TODO: Send travis notifications to hipchat room