# http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# env:
#   - DJANGO_VERSION=1.2.7
#   - DJANGO_VERSION=1.3.1
# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
branches:
  only:
    - master
# TODO: Send travis build notifications to the hipchat room